# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      # - id: no-commit-to-branch
      #   args:
      #     - '-b'
      #     - 'master'
      - id: requirements-txt-fixer
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        # stages: [commit-msg]
        # args: []
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        # language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
