services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION:-1.90.2}
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-n8n-encryption-key}
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      - TZ=${TZ:-Asia/Tehran}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      - EXECUTIONS_PROCESS=${EXECUTIONS_PROCESS:-main}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
      - NODE_ENV=${NODE_ENV:-production}
      # Uncomment to enable basic authentication
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      # - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
    volumes:
      - n8n-data:/home/node/.n8n
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  n8n-data:
    driver: local 