version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=12345678
  mongo-express:
    # https://github.com/mongo-express/mongo-express
    image: mongo-express:1.0.0-alpha.4
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_URL="mongodb://mongodb:27017"
    restart: always
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
