services:
  es01:
    image: elasticsearch:${ES_VERSION:-8.1.2}
    container_name: elasticsearch-dev
    environment:
      - node.name=${ES_NODE_NAME:-es01}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.http.ssl.enabled=false # disable ssl
      - xpack.security.enabled=${ES_DISABLE_SECURITY:-false} # disable authentication
    volumes:
      - es01-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_HTTP_PORT:-9200}:9200
      - ${ES_TRANSPORT_PORT:-9300}:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: kibana:${KIBANA_VERSION:-8.1.2}
    container_name: kibana-dev
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT:-5601}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    depends_on:
      - es01

volumes:
  es01-data:
    driver: local
  kibanadata:
    driver: local
