version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8081:8081"
  reids-ui:
    image: dockerhub.ir/patrikx3/p3x-redis-ui:2022.4.126
    ports:
      - 7843:7843
    volumes:
      - ./.p3xrs-conns.json:/settings/.p3xrs-conns.json:ro
volumes:
  redis-cache:
    driver: local
